### PR TITLE
Feature/magento 2.2

### PR DESCRIPTION
**Pull request by cagartner**
Added support to magento 2.2 #15 

I need some help to test correctly, in Page and Static Block is working  good.

Cheers

### CODE REVIEW

**Comment by sydekumf** [comment]
Hi there,
first of all: Thank you for contributing! That means a lot for us! :-)
I just tried out this pull request in a CE 2.2.0. Have you been able to save cms pages at all, so that the content was saved to the table `cms_page`? I have an empty content field in the table if I create a new cms page.
I did a quick debugging there. For me it seems, that Magento finally uses the so long introduced entity manager which makes the usual `save()`, `load()` etc. functions deprecated. They now do it via the resource model of an entity and the entity manager.
Currently the saving of the content of a cms page is done via a plugin:
```xml
<type name="\Magento\Cms\Model\Page">
        <plugin name="Magenerds_PageDesigner::cmsPageRenderJson"
                type="Magenerds\PageDesigner\Plugin\Cms\Model\Page\PagePlugin" sortOrder="100"/>
    </type>
```
which has `beforeSave()` function. But as the usual `save()` function is no longer used, this will not be executed. So I think, your contribution is great, but we need further debugging and fixes to get the extension work with 2.2 :-)
I think I will debug it further! I am open for help and ideas :-)

**Comment by gewaechshaus** [comment]
@sydekumf - did you already inspect
http://devdocs.magento.com/guides/v2.2/release-notes/changes/ce_changes.html

**Comment by diskocedric** [comment]
Indeed @cagartner I've just try to change plugin declaration to this:
```
<type name="\Magento\Cms\Model\ResourceModel\Page">
        <plugin name="Magenerds_PageDesigner::cmsResourcePageRenderJson"
                type="Magenerds\PageDesigner\Plugin\Cms\Model\ResourceModel\Page\PagePlugin" sortOrder="100"/>
```
And then change the plugin to this:
```
/**
     * Manipulates the Page entity before it is saved
     *
     * @param PageResource $pageResource
     * @param Page $page
     *
     * @return array
     */
    public function beforeSave(PageResource $pageResource, Page $page) // NOSONAR
    {
        /** @noinspection PhpUndefinedMethodInspection */
        $json = $page->getPageDesignerJson();

        if (strlen(trim($json)) > 0) {
            $page->setContent($this->htmlRenderer->toHtml($json));
        }
        return [$page];
    }
```

It does work for me ;)

**Comment by cagartner** [comment]
@diskocedric Thank u for the tip, I went up a new commit with changes and now is able to save in content attr.

**Comment by gewaechshaus** [comment]
@cagartner - many thanks! Now we are able to save the content :)

**Comment by afavata** [comment]
when those changes will take effect in a new release?

**Comment by twosg** [comment]
On Magento 2.2.1 with PHP 7.0.26 I get this when editing a page:

```
mod_fcgid: stderr: PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Magento\\Framework\\View\\Element\\UiComponentFactory::argumentsResolver() must be of the type array, null given, called in /public_html/vendor/magento/framework/View/Element/UiComponentFactory.php on line 233 and defined in /public_html/vendor/magento/framework/View/Element/UiComponentFactory.php:166
mod_fcgid: stderr: Stack trace:
mod_fcgid: stderr: #0 /public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(233): Magento\\Framework\\View\\Element\\UiComponentFactory->argumentsResolver('page-designer', NULL)
mod_fcgid: stderr: #1 /public_html/vendor/magento/module-ui/Component/Form/Field.php(84): Magento\\Framework\\View\\Element\\UiComponentFactory->create('page-designer', 'page_designer', Array)
mod_fcgid: stderr: #2 /public_html/vendor/magento/framework/View/Layout/Generator/UiComponent.php(159): Magento\\Ui\\Component\\Form\\Field->prepare()
mod_fcgid: stderr: #3 /home in /public_html/vendor/magento/framework/View/Element/UiComponentFactory.php on line 166
```

Its because `/vendor/magenerds/pagedesigner/view/adminhtml/ui_component/cms_page_form.xml` declares:
```
<field name="page-designer">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="label" xsi:type="string"/>
                    <item name="source" xsi:type="string">page</item>
                    <item name="dataScope" xsi:type="string">page_designer_json</item>
                    **<item name="formElement" xsi:type="string">page_designer</item>**
                </item>
            </argument>
        </field>
```
where `page_designer` is somehow unknown and has no arguments for the function above.

**Pull request merged**
